# Generated by Django 4.1.3 on 2022-11-11 05:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaravanSaray',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя кемпинга')),
                ('class_type', models.CharField(choices=[('стандарт', 'стандарт'), ('стандарт плюс', 'стандарт плюс'), ('эконом', 'эконом'), ('люкс', 'люкс')], max_length=20, verbose_name='Класс')),
                ('beds', models.CharField(max_length=10, verbose_name='Количество кроватей')),
                ('price_per_1_night', models.FloatField(blank=True, null=True, verbose_name='Цена за 1 ночь')),
                ('price_per_2_nights', models.FloatField(blank=True, null=True, verbose_name='Цена за 2 ночи')),
                ('price_per_3_nights', models.FloatField(blank=True, null=True, verbose_name='Цена за 3 ночи')),
                ('price_per_4_nights', models.FloatField(blank=True, null=True, verbose_name='Цена за 4 ночи')),
                ('price_per_5_nights', models.FloatField(blank=True, null=True, verbose_name='Цена за 5 ночей')),
                ('is_occupied', models.BooleanField(default=False, null=True, verbose_name='Занято')),
            ],
            options={
                'verbose_name': 'Караван Сарай',
                'verbose_name_plural': 'Караван Сараи',
            },
        ),
        migrations.CreateModel(
            name='OrderTour',
            fields=[
                ('individual_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный номер')),
                ('customer_name', models.CharField(max_length=60, verbose_name='Имя заказчика')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Номер телефона')),
                ('chosen_tour', models.CharField(max_length=100, null=True, verbose_name='Выбранный тур')),
                ('date', models.CharField(max_length=50, null=True, verbose_name='Дата тура')),
                ('tourists', models.IntegerField(null=True, verbose_name='Туристов')),
                ('order_bill', models.FloatField(null=True, verbose_name='Счет за тур')),
                ('chosen_car', models.CharField(max_length=100, null=True, verbose_name='Выбранный транспорт')),
                ('questions', models.TextField(null=True, verbose_name='Вопросы к туру')),
                ('order_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Время заказа')),
                ('company_confirmed', models.BooleanField(default=False, null=True, verbose_name='Подтверждено компанией')),
                ('actual', models.BooleanField(default=False, null=True, verbose_name='Актуально')),
                ('is_done', models.BooleanField(default=False, null=True, verbose_name='Исполнено')),
            ],
            options={
                'verbose_name': 'Заказ по туру',
                'verbose_name_plural': 'Заказы по туру',
            },
        ),
        migrations.CreateModel(
            name='Replica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Описание переменной')),
                ('var', models.CharField(max_length=20, verbose_name='Переменная в которой нужно хранить')),
                ('kaz', models.TextField(verbose_name='Казахская реплика')),
                ('rus', models.TextField(verbose_name='Русская реплика')),
                ('eng', models.TextField(verbose_name='Английская реплика')),
            ],
            options={
                'verbose_name': 'Реплика',
                'verbose_name_plural': 'Реплики',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тура')),
                ('car', models.CharField(max_length=100, verbose_name='Автомашина')),
                ('distance', models.FloatField(verbose_name='Расстояние')),
                ('bought_times', models.IntegerField(verbose_name='Сколько раз куплен')),
            ],
            options={
                'verbose_name': 'Тур',
                'verbose_name_plural': 'Туры',
            },
        ),
        migrations.CreateModel(
            name='OrderCamping',
            fields=[
                ('individual_number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Уникальный номер')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('guests', models.IntegerField(verbose_name='Количество гостей')),
                ('date_arrange', models.CharField(max_length=100, verbose_name='Диапазон даты')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('company_confirmed', models.BooleanField(default=False, null=True, verbose_name='Подтверждено компанией')),
                ('actual', models.BooleanField(default=False, null=True, verbose_name='Актуально')),
                ('is_done', models.BooleanField(default=False, null=True, verbose_name='Исполнено')),
                ('caravan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.caravansaray', verbose_name='Выбранный караван')),
            ],
            options={
                'verbose_name': 'Заказ по брони кемпинга',
                'verbose_name_plural': 'Заказы по брони кемпинга',
            },
        ),
    ]
